# Generated by Django 4.0.6 on 2022-07-10 12:12

from django.db import migrations
from django.contrib.auth import get_user_model
import os

def create_super_user(apps, schema_editor):
    User = get_user_model()

    DJANGO_SU_NAME = os.environ.get('DJANGO_SU_NAME')
    DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL')
    DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD')

    User.objects.create_superuser(
        username=DJANGO_SU_NAME,
        email=DJANGO_SU_EMAIL,
        password=DJANGO_SU_PASSWORD
    )

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_login_alter_user_password'),
    ]

    operations = [
        migrations.RunPython(create_super_user)
    ]
